name: xtintas
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_svg: ^1.1.1+1
  email_validator: ^2.0.1
  flutter_modular: ^5.0.3
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  faker: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
